name: Remote Dispatch Action
on: [repository_dispatch]
jobs:
  package-push-gardenlogin:
    if: github.event.client_payload.component == 'gardenlogin'
    runs-on: windows-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' payload '${{ github.event.client_payload.tag }}'"
          echo "Windows gardenlogin binary hash '${{ github.event.client_payload.windows_sha }}'"
      - uses: actions/checkout@v2.1.1
      - name: Update package source files
        run: .github\workflows\update-gardenlogin.ps1 ${{ github.event.client_payload.tag }} ${{ github.event.client_payload.windows_sha }} 
      - name: Choco pack
        uses: crazy-max/ghaction-chocolatey@87d06bbbd2cfb1835f1820042d356aef4875fb5f # pin@v1.6
        with:
          args: pack gardenlogin\gardenlogin.nuspec --version=${{ github.event.client_payload.tag }} -y --outdir gardenlogin
      - name: Choco push
        uses: crazy-max/ghaction-chocolatey@87d06bbbd2cfb1835f1820042d356aef4875fb5f # pin@v1.6
        with:
          args: push "gardenctl-v2\gardenctl-v2.${{ github.event.client_payload.tag }}.nupkg" --source https://chocolatey.org -k secrets.CHOCOLATEY_API_KEY
      - name: Commit files
        run: |
          git config --local user.email "gardener.ci.user@gmail.com"
          git config --local user.name "gardener-robot-ci-1"
          git add "gardenlogin\gardenlogin.${{ github.event.client_payload.tag }}.nupkg"
          git add "gardenlogin\tools\chocolateyinstall.ps1"
          git commit -m "Update gardenlogin"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: false
  package-push-gardenctl-v2:
    if: github.event.client_payload.component == 'gardenctl-v2'
    runs-on: windows-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' payload '${{ github.event.client_payload.tag }}'"
          echo "Windows gardenctl-v2 binary hash '${{ github.event.client_payload.windows_sha }}'"
      - uses: actions/checkout@v2.1.1
      - name: Update package source files
        run: .github\workflows\update-gardenctl-v2.ps1 ${{ github.event.client_payload.tag }} ${{ github.event.client_payload.windows_sha }} 
      - name: Choco pack
        uses: crazy-max/ghaction-chocolatey@87d06bbbd2cfb1835f1820042d356aef4875fb5f # pin@v1.6
        with:
          args: pack gardenctl-v2\gardenctl-v2.nuspec --version=${{ github.event.client_payload.tag }} -y --outdir gardenctl-v2
      - name: Choco push
        uses: crazy-max/ghaction-chocolatey@87d06bbbd2cfb1835f1820042d356aef4875fb5f # pin@v1.6
        with:
          args: push "gardenctl-v2\gardenctl-v2.${{ github.event.client_payload.tag }}.nupkg" --source https://chocolatey.org -k secrets.CHOCOLATEY_API_KEY
      - name: Commit files
        run: |
          git config --local user.email "gardener.ci.user@gmail.com"
          git config --local user.name "gardener-robot-ci-1"
          git add "gardenctl-v2\gardenctl-v2.${{ github.event.client_payload.tag }}.nupkg"
          git add "gardenctl-v2\tools\chocolateyinstall.ps1"
          git commit -m "Update gardenctl-v2"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: false